name: kitapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+4

environment:
    sdk: ^3.5.3

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    firebase_core: ^3.6.0
    firebase_auth: ^5.3.1
    smooth_page_indicator: ^1.2.0+3
    google_fonts: ^6.2.1
    fluttertoast: ^8.2.8
    flutter_animate: ^4.5.0
    firebase_database: ^11.1.4
    cloud_firestore: ^5.4.4
    skeletonizer: ^1.4.2
    google_nav_bar: ^5.0.6
    carousel_slider: ^5.0.0
    provider: ^6.1.2
    uuid: ^4.5.1
    flutter_launcher_icons: ^0.14.1
    flutter_rating_bar: ^4.0.1
    slider_button: ^2.1.0
    google_generative_ai: ^0.4.6
    flutter_dotenv: ^5.2.1
    material_design_icons_flutter: ^7.0.7296
    lottie: ^3.1.3
    syncfusion_flutter_pdf: ^27.2.2
    flutter_cached_pdfview: ^0.4.3
    flutter_pdfview: ^1.3.4
    flutter_cache_manager: ^3.4.1
    syncfusion_flutter_pdfviewer: ^27.2.2
    get: ^4.6.6
    get_storage: ^2.1.1
    percent_indicator: ^4.2.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/animations/
        - .env

    fonts:
        - family: Poppins
          fonts:
              - asset: fonts/Poppins-Thin.ttf
                weight: 100
              - asset: fonts/Poppins-ExtraLight.ttf
                weight: 200
              - asset: fonts/Poppins-Light.ttf
                weight: 300
              - asset: fonts/Poppins-Regular.ttf
                weight: 400
              - asset: fonts/Poppins-Medium.ttf
                weight: 500
              - asset: fonts/Poppins-SemiBold.ttf
                weight: 600
              - asset: fonts/Poppins-Bold.ttf
                weight: 700
              - asset: fonts/Poppins-ExtraBold.ttf
                weight: 800
              - asset: fonts/Poppins-Black.ttf
                weight: 900
        - family: Cy
          fonts:
              - asset: fonts/CyGrotesk-GrandRegular.otf
                weight: 400
              - asset: fonts/CyGrotesk-GrandMedium.otf
                weight: 500
              - asset: fonts/CyGrotesk-GrandBold.otf
                weight: 600
              - asset: fonts/CyGrotesk-GrandDemi.otf
                weight: 700
              - asset: fonts/CyGrotesk-GrandDark.otf
                weight: 800
              - asset: fonts/CyGrotesk-GrandBlack.otf
                weight: 900

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/1024.png"
    min_sdk_android: 23
    adaptive_icon_background: "#fff"
    adaptive_icon_foreground: "assets/images/logo.png"
